feat(git stats): add git repository in the esb conf.
KomodoPlatform/komodo-ecosysboard pull request #2
Opened 2019-07-25 10:18 UTC by Milerius

2019-07-25 12:51 UTC, Milerius commented
This pull request contains update of dependencies.

2019-07-25 12:55 UTC, Milerius commented
Unit tests are now passing @ca333 , only coverage is missing.

2019-07-26 09:07 UTC, ca333 requested changes

2019-07-26 09:07 UTC, ca333 commented on ecosysboard/config/samples/good_config.json
> +  "git_bot_client_id": "d1d63db76668da1141cd",
just leave this config fields empty and replace the strings with `yourClientID` and `yourSecretID` - so whoever runs this software can just use his oauth keys. btw - posting a secret key on github is suboptimal.

2019-07-26 09:07 UTC, ca333 commented on ecosysboard/config/samples/good_config.json
> +        "KomodoPlatform"
VRSC has an own org: https://github.com/veruscoin

2019-07-26 09:07 UTC, ca333 commented on esb_config.json
> +  ],
this list is incomplete - @imylomylo when you get a chance can you please get a list of all KMD related repos that arent listed in our org

2019-07-26 09:16 UTC, ca333 commented on ecosysboard/config/config.go
> +	cfg.GitBotSecretId = "74afa0fe4b377bdfa1d41ddc33147c0042a952b1"
@Milerius ^

2019-07-26 09:26 UTC, ca333 approved these changes

2019-07-26 09:33 UTC, merged